import {
  Job,
  Session,
  HumanTask,
  Operator,
  SystemSettings,
  RetryPolicy,
  ApplicationAttempt,
  AuditLog,
  IntegrationStatusItem,
  UserAccount,
} from '../types.js';

export const initialUserAccounts: UserAccount[] = [
  {
    uid: 'USR-SUPERADMIN-001',
    email: 'zakwanrhmn@gmail.com',
    name: 'Super Admin',
    role: 'SUPERADMIN',
    status: 'ACTIVE',
    mustChangePassword: true,
    failedLoginAttempts: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    uid: 'USR-OP-001',
    email: 'sarah.connor@ops-platform.internal',
    name: 'Sarah Connor',
    role: 'ADMIN',
    status: 'ACTIVE',
    mustChangePassword: false,
    failedLoginAttempts: 0,
    telegramChatId: '984721901',
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    uid: 'USR-OP-002',
    email: 'alex.vance@ops-platform.internal',
    name: 'Alex Vance',
    role: 'SUPERVISOR',
    status: 'ACTIVE',
    mustChangePassword: false,
    failedLoginAttempts: 0,
    telegramChatId: '984721902',
    createdAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    uid: 'USR-OP-003',
    email: 'marcus.brody@ops-platform.internal',
    name: 'Marcus Brody',
    role: 'OPERATOR',
    status: 'ACTIVE',
    mustChangePassword: false,
    failedLoginAttempts: 0,
    telegramChatId: '984721903',
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    uid: 'USR-OP-004',
    email: 'elena.rostova@ops-platform.internal',
    name: 'Elena Rostova',
    role: 'OPERATOR',
    status: 'ACTIVE',
    mustChangePassword: false,
    failedLoginAttempts: 0,
    telegramChatId: '984721904',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    uid: 'USR-VIEWER-001',
    email: 'auditor@ops-platform.internal',
    name: 'Guest Reviewer',
    role: 'VIEWER',
    status: 'ACTIVE',
    mustChangePassword: false,
    failedLoginAttempts: 0,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialOperators: Operator[] = [
  {
    operatorId: 'USR-SUPERADMIN-001',
    name: 'Super Admin (Owner)',
    email: 'zakwanrhmn@gmail.com',
    telegramChatId: '984721900',
    role: 'SUPERADMIN',
    active: true,
    maxConcurrentHumanTasks: 10,
    currentTasksCount: 0,
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    operatorId: 'OP-001',
    name: 'Sarah Connor (Lead Admin)',
    email: 'sarah.connor@ops-platform.internal',
    telegramChatId: '984721901',
    role: 'ADMIN',
    active: true,
    maxConcurrentHumanTasks: 8,
    currentTasksCount: 1,
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    operatorId: 'OP-002',
    name: 'Alex Vance (Supervisor)',
    email: 'alex.vance@ops-platform.internal',
    telegramChatId: '984721902',
    role: 'SUPERVISOR',
    active: true,
    maxConcurrentHumanTasks: 6,
    currentTasksCount: 1,
    createdAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    operatorId: 'OP-003',
    name: 'Marcus Brody (Operator)',
    email: 'marcus.brody@ops-platform.internal',
    telegramChatId: '984721903',
    role: 'OPERATOR',
    active: true,
    maxConcurrentHumanTasks: 4,
    currentTasksCount: 1,
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    operatorId: 'OP-004',
    name: 'Elena Rostova (Operator)',
    email: 'elena.rostova@ops-platform.internal',
    telegramChatId: '984721904',
    role: 'OPERATOR',
    active: true,
    maxConcurrentHumanTasks: 4,
    currentTasksCount: 0,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialSettings: SystemSettings = {
  systemName: "The Keeper's Ops",
  systemDescription: 'Configurable Human-in-the-Loop Browser Engine and Registration Automation Platform',
  timezone: 'UTC',
  concurrencyMode: 'CONFIGURED',
  concurrencyLimit: 12,
  dailyJobLimit: 150,
  queueLimit: 1000,
  autoStartJobs: true,
  defaultPriority: 'NORMAL',
  defaultRunMode: 'AUTO',
  defaultMaxRetries: 3,
  otpTimeoutMinutes: 15,
  humanTaskReminderMinutes: 15,
  humanTaskEscalationMinutes: 60,
  reviewCheckIntervalMinutes: 30,
  maxStatusCheckRetries: 24,
  sessionIdleTimeoutMinutes: 45,
  humanTaskTimeoutMinutes: 120,
  autoRetryTechnicalErrors: true,
  telegramNotificationsEnabled: true,
  telegramRemindersEnabled: true,
  telegramReminderIntervalMinutes: 15,
  telegramEscalationIntervalMinutes: 60,
  emailNotificationsEnabled: true,
  gologinEnabled: true,
  gologinApiUrl: 'https://api.gologin.com',
  gologinCloudUrl: 'https://cloudbrowser.gologin.com',
  gologinConnectionTimeout: 30,
  gologinRequestTimeout: 60,
  gologinMaxRetries: 3,
  gologinRetryBackoff: 2.0,
  authorizedOutlookMailbox: 'operator-checkpoint@domain.com',
  sheetsSyncEnabled: true,
  masterQueueSheet: 'MasterQueue',
  applicationLogSheet: 'ApplicationLogs',
  systemSettingsSheet: 'SystemSettings',
  operatorsSheet: 'Operators',
  notificationLogSheet: 'Notifications',
  sessionRegistrySheet: 'Sessions',
  outlookIntegrationEnabled: true,
  maintenanceMode: false,
  mockMode: true,
  updatedAt: new Date().toISOString(),
  updatedBy: 'SYSTEM_INIT',
};

export const initialRetryPolicies: RetryPolicy[] = [
  {
    policyId: 'POL-NET-01',
    errorCode: 'PROXY_ERROR',
    description: 'Transient proxy connection timeout or handshake stall',
    maxRetries: 3,
    initialDelaySeconds: 30,
    maxDelaySeconds: 300,
    backoffMultiplier: 2.0,
    enabled: true,
    isTechnicalOnly: true,
  },
  {
    policyId: 'POL-NET-01B',
    errorCode: 'ERR_PROXY_TIMEOUT',
    description: 'Transient proxy connection timeout or handshake stall',
    maxRetries: 3,
    initialDelaySeconds: 30,
    maxDelaySeconds: 300,
    backoffMultiplier: 2.0,
    enabled: true,
    isTechnicalOnly: true,
  },
  {
    policyId: 'POL-GL-02',
    errorCode: 'BROWSER_START_TIMEOUT',
    description: 'GoLogin cloud browser container startup failure or port alloc error',
    maxRetries: 3,
    initialDelaySeconds: 45,
    maxDelaySeconds: 400,
    backoffMultiplier: 2.5,
    enabled: true,
    isTechnicalOnly: true,
  },
  {
    policyId: 'POL-GL-02B',
    errorCode: 'ERR_GOLOGIN_STARTUP',
    description: 'GoLogin cloud browser container startup failure or port alloc error',
    maxRetries: 3,
    initialDelaySeconds: 45,
    maxDelaySeconds: 400,
    backoffMultiplier: 2.5,
    enabled: true,
    isTechnicalOnly: true,
  },
  {
    policyId: 'POL-DOM-05',
    errorCode: 'ELEMENT_NOT_FOUND',
    description: 'Transient DOM selector timeout during page rendering',
    maxRetries: 3,
    initialDelaySeconds: 10,
    maxDelaySeconds: 60,
    backoffMultiplier: 1.5,
    enabled: true,
    isTechnicalOnly: true,
  },
  {
    policyId: 'POL-NET-06',
    errorCode: 'NETWORK_TIMEOUT',
    description: 'Transient upstream network gateway or navigation timeout',
    maxRetries: 4,
    initialDelaySeconds: 20,
    maxDelaySeconds: 120,
    backoffMultiplier: 2.0,
    enabled: true,
    isTechnicalOnly: true,
  },
  {
    policyId: 'POL-SHT-03',
    errorCode: 'ERR_SHEETS_QUOTA',
    description: 'Google Sheets API rate limiting (429 Too Many Requests)',
    maxRetries: 5,
    initialDelaySeconds: 15,
    maxDelaySeconds: 180,
    backoffMultiplier: 2.0,
    enabled: true,
    isTechnicalOnly: true,
  },
  {
    policyId: 'POL-TG-04',
    errorCode: 'ERR_TELEGRAM_SEND',
    description: 'Telegram bot delivery network timeout',
    maxRetries: 4,
    initialDelaySeconds: 20,
    maxDelaySeconds: 240,
    backoffMultiplier: 2.0,
    enabled: true,
    isTechnicalOnly: true,
  },
];

export const initialJobs: Job[] = [
  {
    jobId: 'JOB-000001',
    shopName: 'AuraCraft Studios',
    email: 'auracraft.ops@outfit-mail.org',
    passwordReference: 'sec://vault/passwords/auracraft-99',
    proxyReference: 'proxy://us-residential.lum-pool.net:22225:node-us-91',
    gologinProfileId: 'gl_prof_90192',
    gologinProfileName: 'AuraCraft-JOB-000001',
    status: 'QUEUED',
    subStatus: 'WAITING_FOR_WORKER',
    priority: 'HIGH',
    runMode: 'AUTO',
    autoStart: true,
    operatorId: 'OP-001',
    createdAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 2.8).toISOString(),
    retryCount: 0,
    maxRetries: 3,
    currentAttemptNo: 1,
    tags: ['crafts', 'us-east', 'priority-batch'],
    notes: 'Awaiting next available browser execution capacity slot.',
  },
  {
    jobId: 'JOB-000002',
    shopName: 'Nordic Horizon Gear',
    email: 'nordic.h.merch@outfit-mail.org',
    passwordReference: 'sec://vault/passwords/nordic-84',
    proxyReference: 'proxy://us-residential.lum-pool.net:22225:node-eu-12',
    gologinProfileId: 'gl_prof_90193',
    gologinProfileName: 'Nordic-JOB-000002',
    status: 'WAITING_FOR_EMAIL_OTP',
    subStatus: 'AWAITING_HUMAN',
    humanAction: 'Enter 6-digit confirmation code from Outlook mailbox into browser',
    priority: 'CRITICAL',
    runMode: 'SEMI_AUTO',
    autoStart: true,
    operatorId: 'OP-002',
    createdAt: new Date(Date.now() - 3600000 * 1.5).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    startedAt: new Date(Date.now() - 3600000 * 1.4).toISOString(),
    currentSessionId: 'SESS-1002',
    retryCount: 0,
    maxRetries: 3,
    currentAttemptNo: 1,
    tags: ['outdoor', 'us-west', 'requires-otp'],
    notes: 'Browser paused at signup OTP page. Telegram alert dispatched to Alex Vance.',
  },
  {
    jobId: 'JOB-000003',
    shopName: 'Solaris Botanicals',
    email: 'solaris.botanics@outfit-mail.org',
    passwordReference: 'sec://vault/passwords/solaris-71',
    proxyReference: 'proxy://us-residential.lum-pool.net:22225:node-ca-04',
    gologinProfileId: 'gl_prof_90194',
    gologinProfileName: 'Solaris-JOB-000003',
    status: 'WAITING_FOR_REVIEW',
    subStatus: 'REVIEW_POLLING',
    priority: 'NORMAL',
    runMode: 'AUTO',
    autoStart: true,
    operatorId: 'OP-003',
    createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    startedAt: new Date(Date.now() - 3600000 * 4.8).toISOString(),
    submittedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    nextCheckAt: new Date(Date.now() + 1000 * 60 * 25).toISOString(),
    retryCount: 0,
    maxRetries: 24,
    currentAttemptNo: 1,
    tags: ['wellness', 'canada', 'submitted'],
    notes: 'Application submitted cleanly; periodic review monitor scheduled every 30m.',
  },
  {
    jobId: 'JOB-000004',
    shopName: 'Vanguard Audio Lab',
    email: 'vanguard.sound@outfit-mail.org',
    passwordReference: 'sec://vault/passwords/vanguard-19',
    proxyReference: 'proxy://us-residential.lum-pool.net:22225:node-us-02',
    gologinProfileId: 'gl_prof_90195',
    gologinProfileName: 'Vanguard-JOB-000004',
    status: 'APPROVED',
    subStatus: 'SUCCESS',
    priority: 'NORMAL',
    runMode: 'AUTO',
    autoStart: true,
    operatorId: 'OP-001',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1.5).toISOString(),
    startedAt: new Date(Date.now() - 86400000 * 1.9).toISOString(),
    submittedAt: new Date(Date.now() - 86400000 * 1.8).toISOString(),
    completedAt: new Date(Date.now() - 86400000 * 1.5).toISOString(),
    retryCount: 0,
    maxRetries: 3,
    currentAttemptNo: 1,
    tags: ['audio', 'completed', 'approved'],
    notes: 'Merchant approval confirmed via portal check. Synchronized to Google Sheets.',
  },
  {
    jobId: 'JOB-000005',
    shopName: 'Komorebi Tea Collective',
    email: 'komorebi.tea@outfit-mail.org',
    passwordReference: 'sec://vault/passwords/komorebi-42',
    proxyReference: 'proxy://us-residential.lum-pool.net:22225:node-jp-88',
    gologinProfileId: 'gl_prof_90196',
    gologinProfileName: 'Komorebi-JOB-000005',
    status: 'HUMAN_IDENTITY_VERIFICATION',
    subStatus: 'AWAITING_HUMAN',
    humanAction: 'Authorized operator must complete ID document inspection in active session',
    priority: 'HIGH',
    runMode: 'SEMI_AUTO',
    autoStart: true,
    operatorId: 'OP-003',
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    startedAt: new Date(Date.now() - 3600000 * 1.9).toISOString(),
    currentSessionId: 'SESS-1005',
    retryCount: 0,
    maxRetries: 3,
    currentAttemptNo: 2, // Demonstrates reapplication attempt history!
    tags: ['tea', 'identity-checkpoint', 'attempt-2'],
    notes: 'Attempt #1 was rejected due to blurry document; Attempt #2 in progress with verified scan.',
  },
  {
    jobId: 'JOB-000006',
    shopName: 'Zephyr Leather Goods',
    email: 'zephyr.leather@outfit-mail.org',
    passwordReference: 'sec://vault/passwords/zephyr-11',
    proxyReference: 'proxy://us-residential.lum-pool.net:22225:node-us-49',
    gologinProfileId: 'gl_prof_90197',
    gologinProfileName: 'Zephyr-JOB-000006',
    status: 'BROWSER_READY',
    subStatus: 'IN_PROGRESS',
    priority: 'NORMAL',
    runMode: 'AUTO',
    autoStart: true,
    operatorId: 'OP-004',
    createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    startedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    currentSessionId: 'SESS-1006',
    retryCount: 0,
    maxRetries: 3,
    currentAttemptNo: 1,
    tags: ['leather', 'starting'],
    notes: 'Cloud browser instantiated, proxy tunnel verified, navigating to merchant onboarding portal.',
  },
];

export const initialSessions: Session[] = [
  {
    sessionId: 'SESS-1002',
    jobId: 'JOB-000002',
    shopName: 'Nordic Horizon Gear',
    gologinProfileId: 'gl_prof_90193',
    status: 'PAUSED',
    startedAt: new Date(Date.now() - 3600000 * 1.4).toISOString(),
    currentUrl: 'https://sellercentral.platform.example/signup/verify-email',
    currentWorkflowState: 'WAITING_FOR_EMAIL_OTP',
    lastHeartbeat: new Date().toISOString(),
    operatorId: 'OP-002',
    remoteDebuggerUrl: 'http://127.0.0.1:9222/devtools/inspector.html?ws=127.0.0.1:9222/devtools/page/sess-1002',
    cloudBrowserUrl: 'https://cloudbrowser.gologin.com/live/sess-1002-nordic',
    notes: 'Awaiting human operator OTP code entry from Outlook.',
  },
  {
    sessionId: 'SESS-1005',
    jobId: 'JOB-000005',
    shopName: 'Komorebi Tea Collective',
    gologinProfileId: 'gl_prof_90196',
    status: 'PAUSED',
    startedAt: new Date(Date.now() - 3600000 * 1.9).toISOString(),
    currentUrl: 'https://sellercentral.platform.example/verify/identity-upload',
    currentWorkflowState: 'HUMAN_IDENTITY_VERIFICATION',
    lastHeartbeat: new Date().toISOString(),
    operatorId: 'OP-003',
    remoteDebuggerUrl: 'http://127.0.0.1:9222/devtools/inspector.html?ws=127.0.0.1:9222/devtools/page/sess-1005',
    cloudBrowserUrl: 'https://cloudbrowser.gologin.com/live/sess-1005-komorebi',
    notes: 'Identity upload screen active. Operator must complete document submission.',
  },
  {
    sessionId: 'SESS-1006',
    jobId: 'JOB-000006',
    shopName: 'Zephyr Leather Goods',
    gologinProfileId: 'gl_prof_90197',
    status: 'RUNNING',
    startedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    currentUrl: 'https://sellercentral.platform.example/signup/business-info',
    currentWorkflowState: 'BROWSER_READY',
    lastHeartbeat: new Date().toISOString(),
    operatorId: 'OP-004',
    remoteDebuggerUrl: 'http://127.0.0.1:9222/devtools/inspector.html?ws=127.0.0.1:9222/devtools/page/sess-1006',
    cloudBrowserUrl: 'https://cloudbrowser.gologin.com/live/sess-1006-zephyr',
    notes: 'Automated step: entering shop name and registration metadata.',
  },
];

export const initialHumanTasks: HumanTask[] = [
  {
    humanTaskId: 'TASK-9001',
    jobId: 'JOB-000002',
    sessionId: 'SESS-1002',
    taskType: 'EMAIL_OTP',
    title: 'Manual Email OTP Entry: Nordic Horizon Gear',
    description: '1. Access authorized Outlook mailbox nordic.h.merch@outfit-mail.org.\n2. Locate latest verification email.\n3. Enter the 6-digit code directly into the active browser session.\n4. Click "Verify & Continue" in browser, then confirm task completion here.',
    priority: 'CRITICAL',
    status: 'OPEN',
    assignedOperatorId: 'OP-002',
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    dueAt: new Date(Date.now() + 1000 * 60 * 18).toISOString(),
    lastReminderSentAt: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
    reminderCount: 1,
    notes: 'Telegram notification delivered to Alex Vance.',
  },
  {
    humanTaskId: 'TASK-9002',
    jobId: 'JOB-000005',
    sessionId: 'SESS-1005',
    taskType: 'IDENTITY_VERIFICATION',
    title: 'Identity Verification Checkpoint: Komorebi Tea Collective',
    description: 'Authorized operator must inspect and confirm government ID document upload in the active browser session. Do NOT bypass or automate identity documents.',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    assignedOperatorId: 'OP-003',
    createdAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    dueAt: new Date(Date.now() + 1000 * 60 * 42).toISOString(),
    lastReminderSentAt: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    reminderCount: 1,
    notes: 'Marcus Brody opened session; currently completing identity step.',
  },
];

export const initialApplicationAttempts: ApplicationAttempt[] = [
  {
    attemptId: 'ATT-1001-1',
    attemptNo: 1,
    jobId: 'JOB-000004',
    shopName: 'Vanguard Audio Lab',
    email: 'vanguard.sound@outfit-mail.org',
    gologinProfileId: 'gl_prof_90195',
    submittedAt: new Date(Date.now() - 86400000 * 1.8).toISOString(),
    reviewStartedAt: new Date(Date.now() - 86400000 * 1.75).toISOString(),
    finalStatus: 'APPROVED',
    completedAt: new Date(Date.now() - 86400000 * 1.5).toISOString(),
    nextAttemptAllowed: false,
    operatorId: 'OP-001',
    notes: 'First-attempt approval with no inquiries.',
    createdAt: new Date(Date.now() - 86400000 * 1.9).toISOString(),
  },
  {
    attemptId: 'ATT-1005-1',
    attemptNo: 1,
    jobId: 'JOB-000005',
    shopName: 'Komorebi Tea Collective',
    email: 'komorebi.tea@outfit-mail.org',
    gologinProfileId: 'gl_prof_90190',
    submittedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    reviewStartedAt: new Date(Date.now() - 86400000 * 3.8).toISOString(),
    finalStatus: 'REJECTED',
    rejectionReason: 'Document image unreadable or glare detected over legal name.',
    completedAt: new Date(Date.now() - 86400000 * 3.2).toISOString(),
    nextAttemptAllowed: true,
    operatorId: 'OP-002',
    notes: 'Operator requested re-upload with high-resolution scan.',
    createdAt: new Date(Date.now() - 86400000 * 4.1).toISOString(),
  },
  {
    attemptId: 'ATT-1005-2',
    attemptNo: 2,
    jobId: 'JOB-000005',
    shopName: 'Komorebi Tea Collective',
    email: 'komorebi.tea@outfit-mail.org',
    gologinProfileId: 'gl_prof_90196',
    finalStatus: 'PENDING',
    nextAttemptAllowed: true,
    operatorId: 'OP-003',
    notes: 'Second attempt actively ongoing at identity checkpoint.',
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    auditId: 'AUD-001',
    timestamp: new Date(Date.now() - 3600000 * 3).toISOString(),
    actor: 'SYSTEM_SCHEDULER',
    actorRole: 'ADMIN',
    action: 'JOB_CREATED',
    jobId: 'JOB-000001',
    newState: 'QUEUED',
    result: 'SUCCESS',
    metadata: { source: 'GOOGLE_SHEETS_SYNC', rowId: 2 },
  },
  {
    auditId: 'AUD-002',
    timestamp: new Date(Date.now() - 3600000 * 1.5).toISOString(),
    actor: 'WORKFLOW_ENGINE',
    actorRole: 'ADMIN',
    action: 'STATE_TRANSITION',
    jobId: 'JOB-000002',
    sessionId: 'SESS-1002',
    previousState: 'SIGNUP_STARTED',
    newState: 'WAITING_FOR_EMAIL_OTP',
    result: 'SUCCESS',
    reason: 'Detected email verification code checkpoint in browser DOM',
  },
  {
    auditId: 'AUD-003',
    timestamp: new Date(Date.now() - 3600000 * 1.49).toISOString(),
    actor: 'NOTIFICATION_SERVICE',
    actorRole: 'ADMIN',
    action: 'HUMAN_TASK_CREATED',
    jobId: 'JOB-000002',
    humanTaskId: 'TASK-9001',
    newState: 'OPEN',
    result: 'SUCCESS',
    metadata: { channel: 'TELEGRAM', recipient: 'OP-002' },
  },
  {
    auditId: 'AUD-004',
    timestamp: new Date(Date.now() - 86400000 * 1.5).toISOString(),
    actor: 'REVIEW_MONITOR',
    actorRole: 'ADMIN',
    action: 'STATUS_CHECK_POLL',
    jobId: 'JOB-000004',
    previousState: 'WAITING_FOR_REVIEW',
    newState: 'APPROVED',
    result: 'SUCCESS',
    reason: 'Merchant approval confirmed via portal telemetry',
  },
];

export const initialIntegrations: IntegrationStatusItem[] = [
  {
    id: 'firebase',
    name: 'Firebase Firestore',
    status: 'CONNECTED',
    latencyMs: 42,
    lastSuccessfulCall: new Date().toISOString(),
    lastChecked: new Date().toISOString(),
    details: { collections: 15, mode: 'Persistent Store & Cloud Sync' },
  },
  {
    id: 'gologin',
    name: 'GoLogin Cloud Browser API',
    status: 'CONNECTED',
    latencyMs: 88,
    lastSuccessfulCall: new Date().toISOString(),
    lastChecked: new Date().toISOString(),
    details: { activeProfiles: 3, cloudCapacity: 'Dynamic' },
  },
  {
    id: 'telegram',
    name: 'Telegram Bot API',
    status: 'CONNECTED',
    latencyMs: 65,
    lastSuccessfulCall: new Date().toISOString(),
    lastChecked: new Date().toISOString(),
    details: { botHandle: '@WorkflowOperationsBot', webhook: 'Configured' },
  },
  {
    id: 'microsoft_graph',
    name: 'Microsoft Graph / Outlook',
    status: 'CONNECTED',
    latencyMs: 110,
    lastSuccessfulCall: new Date().toISOString(),
    lastChecked: new Date().toISOString(),
    details: { mailboxStatus: 'Healthy', checkpointPolicy: 'Manual Human Entry Only' },
  },
  {
    id: 'google_sheets',
    name: 'Google Sheets Sync API',
    status: 'CONNECTED',
    latencyMs: 145,
    lastSuccessfulCall: new Date().toISOString(),
    lastChecked: new Date().toISOString(),
    details: { sheetsSynced: 6, syncCadence: '10 min / Manual on-demand' },
  },
  {
    id: 'scheduler',
    name: 'Scheduler & Queue Worker',
    status: 'CONNECTED',
    latencyMs: 12,
    lastSuccessfulCall: new Date().toISOString(),
    lastChecked: new Date().toISOString(),
    details: { activeWorkerWorkers: 1, concurrencyLimit: 12, nextRun: 'Dynamic' },
  },
];
